### ISSUE TITLE
Forward-cat over SSL?

### ISSUE THREAD

**Issue by initbar** [danisola/forward-cat#1]
Will there be https in future?

**Comment by danisola** [comment]
Hi initbar, sorry for the delay, I was on holiday. Yes, https is definitely in the roadmap! I'm quite busy at the moment, but hopefully in a month or two will Forward Cat will go over SSL.

**Comment by initbar** [comment]
Nice ;)

**Comment by danisola** [comment]
Forward Cat now only works over https
